version: '3'
services:

  mongo:
    container_name: mongo
    image: mongo:3.6.2
    ports:
      - "27017:27017"

  web:
    build:
      context: .
      args:
        BUILD_ENV: ${BUILD_ENV}
        PORT: ${PORT}
    image: "istore221/athena-dashboard-api:${VERSION}"
    ports:
     - "3000:${PORT}"
    links:
      - mongo
networks:
  default:
    external:
      name: athena
